---
- name: Setup nfs share
  hosts: shareServer
  become: true
  handlers:
    - name: reload nfs
      command: 'exportfs -ra'
  vars:
    nfs_exports:
      - "/exports/fast"
      - "/exports/slow"
  tasks:
    - name: install nfs server package
      package:
        name: nfs-utils
    - name: autostart nfs server
      service:
        name: nfs
        enabled: True
        state: started
    - name: Copy exports file.
      template:
        src: templates/exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644
      notify: reload nfs